// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIphame6fN-cEuD6uX6JtkEZstv9gkMhg',
    appId: '1:927331209183:web:333583f4d24061c08f3e6a',
    messagingSenderId: '927331209183',
    projectId: 'techcare-90149',
    authDomain: 'techcare-90149.firebaseapp.com',
    storageBucket: 'techcare-90149.appspot.com',
    measurementId: 'G-MT59957Q3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC65m9V3_o42boUWw4jFWgKAFQQblY2F_k',
    appId: '1:927331209183:android:ad5074190bf101cd8f3e6a',
    messagingSenderId: '927331209183',
    projectId: 'techcare-90149',
    storageBucket: 'techcare-90149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJlAOgQHjiN2Ywb_n-Osj5opemGfU4bU',
    appId: '1:927331209183:ios:b05a1fa769a696658f3e6a',
    messagingSenderId: '927331209183',
    projectId: 'techcare-90149',
    storageBucket: 'techcare-90149.appspot.com',
    androidClientId: '927331209183-k3om73r8lrip8b5dadsio52nsob8jtf3.apps.googleusercontent.com',
    iosClientId: '927331209183-7430908a05gfe6vjk0s3er4fr921k92e.apps.googleusercontent.com',
    iosBundleId: 'com.example.techCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJlAOgQHjiN2Ywb_n-Osj5opemGfU4bU',
    appId: '1:927331209183:ios:e4f4d8097b6042988f3e6a',
    messagingSenderId: '927331209183',
    projectId: 'techcare-90149',
    storageBucket: 'techcare-90149.appspot.com',
    androidClientId: '927331209183-k3om73r8lrip8b5dadsio52nsob8jtf3.apps.googleusercontent.com',
    iosClientId: '927331209183-2pa8a8llo1tsh3djpkceis5a8lc4jjh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.techCare.RunnerTests',
  );
}
